#!/bin/bash

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication surfaceFeatures
runApplication decomposePar -noFields

# Run in parallel
# runParallel snappyHexMesh -overwrite -parallel
mpirun -np 6 snappyHexMesh -overwrite -parallel > log.snappy 2>&1

# runParallel createBaffles -overwrite 
# runParallel splitBaffles -overwrite 

runParallel checkMesh -parallel
# runParallel renumberMesh -overwrite -parallel

runApplication reconstructPar